### CS4622 Mini Kaggle Competition - Classification
#### Author: Sabine Hollatz

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import statsmodels.formula.api as smf
import statsmodels.api as sm
from sklearn import preprocessing, metrics
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import linear_model
from sklearn.tree import DecisionTreeClassifier
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus

import seaborn as sns

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


### Loading the Data and Preprocessiong

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [3]:
df_train = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/stock_XY_train.csv')
df_train.head()

Unnamed: 0 Ticker       Revenue  ...              Sector  Yr  Buy
0        4685   MGEN  2.538000e+06  ...          Healthcare  15    0
1        3142     SO  1.846700e+10  ...           Utilities  14    1
2       15877   ONDK  3.509500e+08  ...  Financial Services  17    0
3        6977   FFNW  3.392500e+07  ...  Financial Services  15    1
4        8237    IFF  3.116350e+09  ...     Basic Materials  16    1

[5 rows x 226 columns]

In [4]:
df_train = df_train.drop(['Unnamed: 0', 'Ticker', 'Yr'], axis=1)
df_train.head()

Revenue  Revenue Growth  ...              Sector  Buy
0  2.538000e+06         -0.4125  ...          Healthcare    0
1  1.846700e+10          0.0808  ...           Utilities    1
2  3.509500e+08          0.2047  ...  Financial Services    0
3  3.392500e+07         -0.0320  ...  Financial Services    1
4  3.116350e+09          0.0308  ...     Basic Materials    1

[5 rows x 223 columns]

In [5]:
df_val = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/stock_X_test.csv')
df_val.head()

Unnamed: 0  Unnamed: 0.1 Ticker  ...  SG&A Expenses Growth             Sector  Yr
0           0         17685  CMCSA  ...                0.1308  Consumer Cyclical  18
1           1         17686    KMI  ...               -0.1265             Energy  18
2           2         17687   INTC  ...               -0.0942         Technology  18
3           3         17688     MU  ...                0.0942         Technology  18
4           4         17689     GE  ...                0.0308        Industrials  18

[5 rows x 226 columns]

In [6]:
df_val = df_val.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Ticker', 'Yr'], axis=1)
df_val.head()

Revenue  Revenue Growth  ...  SG&A Expenses Growth             Sector
0  9.450700e+10          0.1115  ...                0.1308  Consumer Cyclical
1  1.414400e+10          0.0320  ...               -0.1265             Energy
2  7.084800e+10          0.1289  ...               -0.0942         Technology
3  3.039100e+10          0.4955  ...                0.0942         Technology
4  1.216150e+11          0.0285  ...                0.0308        Industrials

[5 rows x 222 columns]

In [7]:
df_train.dtypes

Revenue                 float64
Revenue Growth          float64
Cost of Revenue         float64
Gross Profit            float64
R&D Expenses            float64
                         ...   
Debt Growth             float64
R&D Expense Growth      float64
SG&A Expenses Growth    float64
Sector                   object
Buy                       int64
Length: 223, dtype: object

In [0]:
df_train['Sector'] = df_train['Sector'].astype('category')

In [9]:
df_train.dtypes

Revenue                  float64
Revenue Growth           float64
Cost of Revenue          float64
Gross Profit             float64
R&D Expenses             float64
                          ...   
Debt Growth              float64
R&D Expense Growth       float64
SG&A Expenses Growth     float64
Sector                  category
Buy                        int64
Length: 223, dtype: object

In [10]:
df_train.isna().sum()

Revenue                  796
Revenue Growth          1379
Cost of Revenue         1103
Gross Profit             794
R&D Expenses            1353
                        ... 
Debt Growth             1649
R&D Expense Growth      1565
SG&A Expenses Growth    1531
Sector                     0
Buy                        0
Length: 223, dtype: int64

In [0]:
# split predictors and response variable
X_train = df_train.drop('Buy', axis=1)
y_train = df_train['Buy']

In [0]:
# get quantitative features to fill missing values with the feature mean. No missing values in qualitative 
# feature 'Sector'.
X_train_quant = X_train.drop('Sector', axis=1)
columns_quant = list(X_train_quant.columns.values)

X_train[columns_quant] = X_train[columns_quant].transform(lambda x: x.fillna(x.mean()))

In [13]:
X_train.isna().sum()

Revenue                        0
Revenue Growth                 0
Cost of Revenue                0
Gross Profit                   0
R&D Expenses                   0
                              ..
Book Value per Share Growth    0
Debt Growth                    0
R&D Expense Growth             0
SG&A Expenses Growth           0
Sector                         0
Length: 222, dtype: int64

In [14]:
X_train.isnull().sum()

Revenue                        0
Revenue Growth                 0
Cost of Revenue                0
Gross Profit                   0
R&D Expenses                   0
                              ..
Book Value per Share Growth    0
Debt Growth                    0
R&D Expense Growth             0
SG&A Expenses Growth           0
Sector                         0
Length: 222, dtype: int64

In [0]:
# fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(20,10))
# ax.boxplot(X_train[columns_quant[:56]])
# # ax[1].boxplot(X_train[columns_quant[56:111]], labels=columns_quant[56:111])
# # ax[2].boxplot(X_train[columns_quant[111:167]], labels=columns_quant[111:167])
# # ax[3].boxplot(X_train[columns_quant[167:]], labels=columns_quant[167:])
# plt.xticks(rotation=90);

In [0]:
def outlierCheck(df, attr):
    outlier_indices = []
    outlier_values = []
    inlier_indices = []
    q1 = df[attr].quantile(.25)
    q3 = df[attr].quantile(.75)
    iqr = q3 - q1
    
    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)
    
    for index, row in df.iterrows():
        if row[attr] > upper_bound:
            outlier_indices.append(index)
            outlier_values.append(row[attr])
        elif row[attr] < lower_bound:
            outlier_indices.append(index)
            outlier_values.append(row[attr])
        else:
            inlier_indices.append(index)
    return inlier_indices, outlier_indices, outlier_values

In [0]:
# outliers = []
# for feature in columns_quant:
#     inlier, outlier, _ = outlierCheck(X_train, feature)
#     print("In train_X feature {} are {} outliers".format(feature, len(outlier)))
# print("")

In [18]:
# normalize quantitative features
min_max_scaler = preprocessing.MinMaxScaler()
X_train_scaled = X_train.copy(deep=True)

for attr in columns_quant:
    X_train_scaled[attr] = min_max_scaler.fit_transform(X_train_scaled[attr].values.reshape(-1,1))
X_train_scaled.head()

Revenue  Revenue Growth  ...  SG&A Expenses Growth              Sector
0  0.000346        0.000293  ...              0.007499          Healthcare
1  0.010472        0.000305  ...              0.006418           Utilities
2  0.000537        0.000308  ...              0.005871  Financial Services
3  0.000363        0.000302  ...              0.006866  Financial Services
4  0.002053        0.000304  ...              0.006901     Basic Materials

[5 rows x 222 columns]

### Training Binary Classifiers

#### Stochastic Gradient Descent classifier

In [19]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=7)
sgd_clf.fit(X_train[columns_quant], y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=7, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [20]:
cross_val_score(sgd_clf, X_train[columns_quant], y_train, cv=5, scoring="accuracy")

array([0.51655897, 0.44870759, 0.4503231 , 0.44749596, 0.44040404])

In [21]:
y_train_pred = cross_val_predict(sgd_clf, X_train[columns_quant], y_train, cv=5)
metrics.confusion_matrix(y_train, y_train_pred)

array([[2541, 3437],
       [3239, 3162]])

In [22]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=7)
sgd_clf.fit(X_train_scaled[columns_quant], y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=7, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [23]:
cross_val_score(sgd_clf, X_train_scaled[columns_quant], y_train, cv=5, scoring="accuracy")

array([0.48344103, 0.51938611, 0.51857835, 0.48182553, 0.52282828])

In [24]:
log_reg = linear_model.LogisticRegressionCV(solver='lbfgs', max_iter=10000).fit(X_train_scaled[columns_quant], y_train)
y_hat_log_reg = cross_val_predict(log_reg, X_train_scaled[columns_quant], y_train, cv=5)
metrics.confusion_matrix(y_train, y_hat_log_reg)

array([[2183, 3795],
       [1619, 4782]])

In [25]:
cross_val_score(log_reg, X_train_scaled[columns_quant], y_train, cv=5, scoring="accuracy")

array([0.58037157, 0.55977383, 0.54644588, 0.56785137, 0.55878788])